Algoritmo "CemInteiros"
// Disciplina   : [Linguagem e Lï¿½gica de Programaï¿½
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
   contadora, soma:inteiro

Inicio
   para contadora de 1 ate 100 passo 1 faca
      soma <- soma + contadora
   fimpara
         escreva(soma)
Fimalgoritmo