Algoritmo "cronometro"
// Disciplina   : [Linguagem e Lï¿½gica de Programaï¿½
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
   contadora, contadora1: inteiro
Inicio
   para contadora de 0 ate 59 passo 1 faca
      para contadora1 de 0 ate 59 passo 1 faca
           escreval(contadora, ":", contadora1)
      fimpara
   fimpara
Fimalgoritmo