Algoritmo "estrutura_decisao_simples"
// Disciplina   : [Linguagem e Lï¿½gica de Programaï¿½
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Estrutura de decisão simples
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2024
Var
   numero: inteiro

Inicio
   escreval("Digite um numero: ")
   leia(numero)
   se numero < 10 entao
      escreval("numero menor que 10")
   fimse
Fimalgoritmo