Algoritmo "SomaPares"
// Disciplina   : [Linguagem e Lï¿½gica de Programaï¿½
// Professor   : Antonio Carlos Nicolodi

// Descrição   : Elaborar um programa que apresente no final o somatório
//dos valores pares existentes na faixa de 1 até 500

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
   contadora, soma: inteiro

Inicio
   para contadora de 0 ate 100 passo 2 faca
   soma<- soma + contadora
   fimpara
   escreva(soma)

Fimalgoritmo