Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lï¿½gica de Programaï¿½
// Professor   : Antonio Carlos Nicolodi
// Descrição   :uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
   contadora, numero:inteiro

Inicio
   escreval("Qual a tabuada requisitada?")
   leia(numero)
   para contadora de 1 ate 10 faca
   escreval(numero, " * ", contadora, " = ", contadora*numero)
   fimpara
Fimalgoritmo